name: Kraken Graphics
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7080809285398573
title: Kraken Graphics
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-69613811-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3d7ae'
    - '#625a58'
    - '#c6ad96'
    - '#837a71'
    - '#ad9b83'
  brandStrength: 0
  lightness: 0.022513940930366516
  saturation: 0.6230966956354678
  rhythmicContrast: 0.5812760004773736
purpose: []
