name: Kraken Graphics
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7080809285398573
title: Kraken Graphics
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.022513940930366516
  saturation: 0.6230966956354678
  rhythmicContrast: 0.5812760004773736
purpose: []
