name: Kraken Graphics
favicon: null
layout_spectrum: 0.48021
typography_spectrum: 0.75235
title: Kraken Graphics
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-69613811-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000101'
    - '#174e4b'
    - '#257976'
    - '#88a17d'
    - '#617760'
  brandStrength: 0.5
  lightness: 0.022513940930366516
  saturation: 0
  rhythmicContrast: 0
purpose: []
