title: Kraken Graphics
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6230966956354678
  brandStrength: 0
  rhythmicContrast: 0.5812760004773736
  brandColors: []
  lightness: 0.02251394093036652
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-69613811-1
  facebook: null
favicon: null
name: Kraken Graphics
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.9919441
layout_spectrum: 1
